#! /bin/sh
nitrogen --restore
$HOME/.config/polybar/launch.sh # Bar

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focused_border_color "#8C7868"
bspc config normal_border_color "#2B2B2B"
bspc config active_border_color "#cc241d"

bspc config border_width         1
bspc config window_gap           5
bspc config pointer_modifier mod4

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off
  
nm-applet & compton # Internet selector
xset r rate 300 50 # making keys feel smoother 
